degradation_1:
  random_blur:
    params:
      kernel_size: [ 7, 9, 11, 13, 15, 17, 19, 21 ]
      kernel_list: [ 'iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso', 'sinc' ]
      kernel_prob: [ 0.405, 0.225, 0.108, 0.027, 0.108, 0.027, 0.1 ]
      sigma_x: [ 0.2, 3 ]
      sigma_y: [ 0.2, 3 ]
      rotate_angle: [ -3.1416, 3.1416 ]
      beta_gaussian: [ 0.5, 4 ]
      beta_plateau: [ 1, 2 ]
      sigma_x_step: 0.02
      sigma_y_step: 0.02
      rotate_angle_step: 0.31416
      beta_gaussian_step: 0.05
      beta_plateau_step: 0.1
      omega_step: 0.0628
    keys: [ 'lqs' ]
  random_resize:
    params:
      resize_mode_prob: [ 0.2, 0.7, 0.1 ]  # up, down, keep
      resize_scale: [ 0.15, 1.5 ]
      resize_opt: [ 'bilinear', 'area', 'bicubic' ]
      resize_prob: [ 0.3333, 0.3333, 0.3334 ]
      resize_step: 0.015
      is_size_even: True
    keys: [ 'lqs' ]
  random_noise:
    params:
      noise_type: [ 'gaussian', 'poisson' ]
      noise_prob: [ 0.5, 0.5 ]
      gaussian_sigma: [ 1, 30 ]
      gaussian_gray_noise_prob: 0.4
      poisson_scale: [ 0.05, 3 ]
      poisson_gray_noise_prob: 0.4
      gaussian_sigma_step: 0.1
      poisson_scale_step: 0.005
    keys: [ 'lqs' ]
  random_jpeg:
    params:
      quality: [ 30, 95 ]
      quality_step: 3
    keys: [ 'lqs' ]
  random_mpeg:
    params:
      codec: [ 'libx264', 'h264', 'mpeg4' ]
      codec_prob: [ 0.3333, 0.3333, 0.3334 ]
      bitrate: [ !!float 1e4, !!float 1e5 ]
    keys: [ 'lqs' ]

degradation_2:
  random_blur:
    params:
      prob: 0.8
      kernel_size: [ 7, 9, 11, 13, 15, 17, 19, 21 ]
      kernel_list: [ 'iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso', 'sinc' ]
      kernel_prob: [ 0.405, 0.225, 0.108, 0.027, 0.108, 0.027, 0.1 ]
      sigma_x: [ 0.2, 1.5 ]
      sigma_y: [ 0.2, 1.5 ]
      rotate_angle: [ -3.1416, 3.1416 ]
      beta_gaussian: [ 0.5, 4 ]
      beta_plateau: [ 1, 2 ]
      sigma_x_step: 0.02
      sigma_y_step: 0.02
      rotate_angle_step: 0.31416
      beta_gaussian_step: 0.05
      beta_plateau_step: 0.1
      omega_step: 0.0628
    keys: [ 'lqs' ]
  random_resize:
    params:
      resize_mode_prob: [ 0.3, 0.4, 0.3 ]  # up, down, keep
      resize_scale: [ 0.3, 1.2 ]
      resize_opt: [ 'bilinear', 'area', 'bicubic' ]
      resize_prob: [ 0.3333, 0.3333, 0.3334 ]
      resize_step: 0.03
      is_size_even: True
    keys: [ 'lqs' ]
  random_noise:
    params:
      noise_type: [ 'gaussian', 'poisson' ]
      noise_prob: [ 0.5, 0.5 ]
      gaussian_sigma: [ 1, 25 ]
      gaussian_gray_noise_prob: 0.4
      poisson_scale: [ 0.05, 2.5 ]
      poisson_gray_noise_prob: 0.4
      gaussian_sigma_step: 0.1
      poisson_scale_step: 0.005
    keys: [ 'lqs' ]
  random_jpeg:
    params:
      quality: [ 30, 95 ]
      quality_step: 3
    keys: [ 'lqs' ]
  random_mpeg:
    params:
      codec: [ 'libx264', 'h264', 'mpeg4' ]
      codec_prob: [ 0.3333, 0.3333, 0.3334 ]
      bitrate: [ !!float 1e4, !!float 1e5 ]
    keys: [ 'lqs' ]
  resize_final:
    params:
      target_size: [ 135, 240 ]   #128  128
      resize_opt: [ 'bilinear', 'area', 'bicubic' ]
      resize_prob: [ 0.3333, 0.3333, 0.3334 ]
    keys: [ 'lqs' ]
  blur_final:
    params:
      prob: 0.8
      kernel_size: [ 7, 9, 11, 13, 15, 17, 19, 21 ]
      kernel_list: [ 'sinc' ]
      kernel_prob: [ 1 ]
      omega: [ 1.0472, 3.1416 ]
      omega_step: 0.0628
    keys: [ 'lqs' ]